<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('classcode', 'classcode', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('dbase','database','hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetCheck('translated','translated', 'open')</script> </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('publisher','publisher','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pubplace','publication place', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetFromTo('pubdate','publication date', 'hidden')</script>    </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('title','title','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','title-id', 'hidden')</script> </td>
 </tr>
</table>
<table>
<hr>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('author','author', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('translator','translator','hidden')</script></td>
 </tr>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('langvariety','language variety', 'hidden')</script></td>
 </tr>
</table>
