<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid', 'id', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('name','author','hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('location','location','hidden')</script></td>

 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('category','category','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('urgency','urgency', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetFromTo('time','time', 'hidden', 'format: yyyy-mm-dd hh:mm:ss')</script> </td>
 </tr>
</table>


