


<input type="hidden" name="phrase_0_corpus" value="ILN_LEKS"></input>







<table>


 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('title','tittel','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','tittel-id', 'hidden')</script> </td>
 </tr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('collection','samling','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('text-type','type', 'hidden')</script></td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('issnisbn','issn/isbn','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('publisher','utgiver','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pubplace','utgivelsessted', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetFromTo('pubdate','utgivelsesår', 'hidden')</script>    </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('kategori', 'kategori', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('emne','emne','hidden')</script></td>
 </tr>
</table>
<table>
<hr>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('name','navn', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('geogr','fødested','hidden')</script></td>
 </tr>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('auth-type','type', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('auth-gender','kjønn','hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetFromTo('age','fødselsår', 'hidden')</script></td>
 </tr>
</table>
