<br/><br />

<h3>Konkplus</h3>
Longitudinellt tidningsmaterial från några svenska dagstidningar.<br />
Förvaltas och utvecklas av Språkbanken<br>
Institutionen för svenska språket<br>
Göteborgs universitet<br> 
<br /><br />

 <? echo "<a href='http://spraakbanken.gu.se/'><img style='border-style: none' src='http://spraakbanken.gu.se/bilder/sbli.gif' /></a>"; ?> 

<br /><br />

 <? echo "<a href='http://www.gu.se/'><img style='border-style: none' src='http://spraakbanken.gu.se/bilder/LOGUcen2r.gif' /></a>"; ?> 

