<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid', 'id', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('st', 'token', 'hidden')</script></td>
 </tr>
</table>
<table>
<hr>
 <tr>
 <td valign="top"><script language="javascript">writeWidgetDoubleTable('kt','konktoken', 'hidden')</script> </td> 
 <td valign="top"><script language="javascript">writeWidgetDoubleTable('co','korpus', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pt','del/avdelning','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetFromTo('time','tidpunkt', 'hidden', 'format: yyyy-mm-dd')</script> </td>
 </tr>
</table>


