








<table>


 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script> </td>

 </tr>
</table>
<hr>
<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('bred','oppvokst','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('abode','bosted','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('longest','bodd lengst', 'hidden')</script></td>

 </tr>
</table>
<table>
<hr>
 <tr>

  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pro','yrke', 'hidden')</script></td>
   <td valign="top"><script language="javascript">writeWidgetFromTo('age','alder', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetCheck('sex','kjønn', 'hidden')</script> </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetCheck('edu','utdannelse', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetFromTo('eduyears','utdannelse (år)', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetCheck('intendedu','tenkt utdannelse', 'hidden')</script>    </td>
</tr><tr>
  <td valign="top"><script language="javascript">writeWidgetCheck('medu','fars utdannelse', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetCheck('fedu','mors utdannelse', 'hidden')</script>    </td>

 </tr>
</table>
<table>


 <tr>



 </tr>

 <tr>

 </tr>
</table>
