<br>
<br>
<h3>The Oslo Multilingual Corpus</h3>
Developed by <a href='http://www.hf.uio.no/forskningsprosjekter/sprik/english/index.html'>The Sprik project</a>,<br> in cooperation with <a href='http://www.hf.uio.no/tekstlab/'>The Text Laboratory</a>.
<br><br>
<a href='http://www.hf.uio.no/forskningsprosjekter/sprik/english/index.html'><img style='border-style: none' src='http://www.hf.uio.no/forskningsprosjekter/sprik/img/SPRIK-liten-logo-org.gif' /></a>
<br><br>
 <? echo "<a href='http://www.hf.uio.no/tekstlab'><img style='border-style: none' src='" . $htmlRoot . "/img/logo.png' /></a>"; ?> 

<br><br>

 <? echo "<a href='http://www.hf.uio.no/iln'><img style='border-style: none' src='" . $htmlRoot . "/img/logo-uio.png' /></a>"; ?> 