<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('collection','collection', 'hidden')</script> </td>
 </tr>
</table>
<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('title','title', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','text-id', 'hidden')</script> </td>
 </tr>

</table>
<table>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('genre','genre', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('year','year published', 'hidden')</script> </td>


 </tr>

 <tr>

  <td valign="top"><script language="javascript">writeWidgetDoubleTable('born','year born', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('name','author', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('sex','gender', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('nationality','nationality', 'hidden')</script> </td>

 </tr>

</table>
