<br>
<br>
<h3>Sami-Norwegian Parallel Corpus</h3>
Developed by  <a href='http://giellatekno.uit.no/english.html'>Sami language technology project</a>,<br> in cooperation with <a href='http://www.hf.uio.no/tekstlab/'>The Text Laboratory</a>.
<br><br>
<a href='http://giellatekno.uit.no/english.html'><img style='border-style: none' src='http://giellatekno.uit.no/images/project.png'></a>

<br><br>

 <?php echo "<a href='http://www.hf.uio.no/tekstlab'><img style='border-style: none' src='http://omilia.uio.no/glossa/html/img/logo.png' /></a>"; ?> 
