<table>
  <tr>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script>
    </td>
  </tr>
</table>
<hr />
<table width="100%" border="0">
  <tr>
    <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('country','country','hidden')</script>
    </td>
    <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('region','region','hidden')</script>
    </td>
        <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('area','area','hidden')</script>
    </td>
    <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('place','place','hidden')</script>
    </td>
   </tr>
</table>
<table>
<hr />
<table>
  <tr>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('agegroup','agegroup', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('sex','sex', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('rec','rec (year)', 'hidden')</script>
    </td>

    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('genre','genre', 'hidden')</script>
    </td>

  </tr>
</table> 