<br>
<br>
<h3>Developmental processes <br>in urban linguistic environments<br> - convergence and divergence<br> (UPUS)</h3>
Developed by  <a href='http://www.hf.ntnu.no/hf/adm/forskning/prosjekter/UPUS'>The UPUS project</a>,<br> in cooperation with <a href='http://www.hf.uio.no/tekstlab/'>The Text Laboratory</a>.
<br><br>
<a href='http://www.hf.ntnu.no/hf/adm/forskning/prosjekter/UPUS'><img style='border-style: none' src='http://www.hf.ntnu.no/hf/adm/forskning/prosjekter/UPUS/grafikk/UPUSturkis.gif'></a>

<br><br>

<a href='http://www.hf.uio.no/tekstlab'><img style='border-style: none' src='http://omilia.uio.no/glossa/html/img/logo.png' /></a>
