








<table>


 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script> </td>

 </tr>
</table>
<hr>
<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('place','place','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('agegroup','agegroup','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('raised','raised', 'hidden')</script></td>

 </tr>
</table>
<table>
<hr>
 <tr>

  <td valign="top"><script language="javascript">writeWidgetDoubleTable('parents','parents', 'hidden')</script></td>
   <td valign="top"><script language="javascript">writeWidgetDoubleTable('sex','gender', 'hidden')</script>    </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('lang','language', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('langs','languages', 'hidden')</script>    </td>

 </tr>
</table>
<table>


 <tr>



 </tr>

 <tr>

 </tr>
</table>
